LouisvilleKendo/Models/ClubMember.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace LouisvilleKendo.Models
{
    public class ClubMember
    {
        public int ID { get; set; }
        public int AuskfId { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public DateTime StartDate { get; set; }
        public string Rank { get; set; }
        public bool FederationMember { get; set; }
        public bool CurrentMember { get; set; }
    }
}

LouisvilleKendo/Controllers/ClubMemberController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LouisvilleKendo.DAL;
using LouisvilleKendo.Models;

namespace LouisvilleKendo.Controllers
{
    public class ClubMemberController : Controller
    {
        private ClubContext db = new ClubContext();

        // GET: ClubMember
        public ActionResult Index()
        {
            return View(db.ClubMembers.ToList());
        }

        // GET: ClubMember/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ClubMember clubMember = db.ClubMembers.Find(id);
            if (clubMember == null)
            {
                return HttpNotFound();
            }
            return View(clubMember);
        }

        // GET: ClubMember/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ClubMember/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,AuskfId,LastName,FirstName,StartDate,Rank,FederationMember,CurrentMember")] ClubMember clubMember)
        {
            if (ModelState.IsValid)
            {
                db.ClubMembers.Add(clubMember);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(clubMember);
        }

        // GET: ClubMember/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ClubMember clubMember = db.ClubMembers.Find(id);
            if (clubMember == null)
            {
                return HttpNotFound();
            }
            return View(clubMember);
        }

        // POST: ClubMember/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,AuskfId,LastName,FirstName,StartDate,Rank,FederationMember,CurrentMember")] ClubMember clubMember)
        {
            if (ModelState.IsValid)
            {
                db.Entry(clubMember).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(clubMember);
        }

        // GET: ClubMember/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ClubMember clubMember = db.ClubMembers.Find(id);
            if (clubMember == null)
            {
                return HttpNotFound();
            }
            return View(clubMember);
        }

        // POST: ClubMember/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ClubMember clubMember = db.ClubMembers.Find(id);
            db.ClubMembers.Remove(clubMember);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LouisvilleKendo/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LouisvilleKendo.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "About Louisville Kendo Club";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Please contact us for information";

            return View();
        }
    }
}

LouisvilleKendo/Views/ClubMember/Create.cshtml
@model LouisvilleKendo.Models.ClubMember

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ClubMember</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.AuskfId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AuskfId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AuskfId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Rank, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Rank, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Rank, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FederationMember, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.FederationMember)
                    @Html.ValidationMessageFor(model => model.FederationMember, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CurrentMember, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.CurrentMember)
                    @Html.ValidationMessageFor(model => model.CurrentMember, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LouisvilleKendo/Views/ClubMember/Delete.cshtml
@model LouisvilleKendo.Models.ClubMember

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ClubMember</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.AuskfId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AuskfId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Rank)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rank)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FederationMember)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FederationMember)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CurrentMember)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CurrentMember)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

LouisvilleKendo/Views/ClubMember/Details.cshtml
@model LouisvilleKendo.Models.ClubMember

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>ClubMember</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.AuskfId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AuskfId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Rank)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rank)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FederationMember)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FederationMember)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CurrentMember)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CurrentMember)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

LouisvilleKendo/Views/ClubMember/Edit.cshtml
@model LouisvilleKendo.Models.ClubMember

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ClubMember</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.AuskfId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AuskfId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AuskfId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Rank, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Rank, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Rank, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FederationMember, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.FederationMember)
                    @Html.ValidationMessageFor(model => model.FederationMember, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CurrentMember, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.CurrentMember)
                    @Html.ValidationMessageFor(model => model.CurrentMember, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LouisvilleKendo/Views/ClubMember/Index.cshtml
@model IEnumerable<LouisvilleKendo.Models.ClubMember>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.AuskfId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StartDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Rank)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FederationMember)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CurrentMember)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.AuskfId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StartDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Rank)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FederationMember)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CurrentMember)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>

LouisvilleKendo/Views/Home/About.cshtml
<h2>@ViewBag.Title</h2>
<h3>@ViewBag.Message</h3>

<!-- About, Practice Times, Map -->
<div class="container">
    <div class="row">
        <div class="col">
            <div class="about">
                @*<h3>About Louisville Kendo</h3>*@
                <p> Louisville Kendo Club is the local Kendo club for the greater Louisville area. Founded in 2004, Louisville Kendo Club is a non-profit organization dedicated to the practice and teaching of kendo and is affiliated with the East Central U.S. Kendo Federation (ECUSKF) and is part of the All United States Kendo Federation (AUSKF).<br> </p>
                <p style="padding-top: .5em">The concept and purpose of practicing kendo, according the All Japan Kendo Federation: </p>

                <b>Concept </b><br>
                Kendo is a way to discipline the human character through the application of the principles of the katana.<br>

                <p>
                    <b>Purpose</b><br>
                    To mold the mind and body.<br>
                    To cultivate a vigorous spirit<br>
                    And through correct and rigid training,<br>
                    To strive for improvement in the art of Kendo.<br>
                    To hold in esteem human courtesy and honor.<br>
                    To associate with others with sincerity.<br>
                    And to forever pursue the cultivation of oneself.<br>
                    Thus will one be able:<br>
                    To love one's country and society;<br>
                    To contribute to the development of culture;<br>
                    And to promote peace and prosperity among all peoples.
                </p>
            </div>
        </div>

        <div class="col">
            <div class="timesLocation">
                <h3>Practice times</h3>
                <p><b>Saturday</b> 10:00AM-12:00PM<br> <b>Wednesday</b> 7:30PM-9:30PM</p>
                <p>These are our regular practice times.  However, occassionaly we are out of town or may have to cancel practice for some reason, so please contact us to ensure we will be having practice on a given day.</p> <br>
                <h3>Where we are located</h3>
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3134.5657967160446!2d-85.56678748569377!3d38.21997629419497!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x88690ca80f38a6df%3A0x20ecdb722f14e9c7!2sLouisville+Kendo+Club!5e0!3m2!1sen!2sus!4v1519591810468" width="400" height="300" frameborder="0" style="border:0" allowfullscreen></iframe>
            </div>
        </div>
    </div>
</div>
<!-- End About, Practice Times, Map -->

LouisvilleKendo/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    1932 Production Dr.<br />
    Louisville, KY 40299<br />
    <abbr title="Phone">P:</abbr>
    (502)640-8920
</address>

<address>
    <strong>Email:</strong>   <a href="kendoka69@mac.com">kendoka69@mac.com</a><br />
</address>

LouisvilleKendo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Louisville Kendo Club</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>

    <nav class="navbar navbar-dark fixed-top" style="background-color: #3d5b95;">
        @Html.ActionLink("Louisville Kendo Club", "Index", "Home", null, new { @class = "navItem" })
        <button class="navbar-toggler ml-auto custom-toggler" type="button" data-toggle="collapse" data-target="#collapsingNavbar4">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="navbar-collapse collapse" id="collapsingNavbar4">
            <ul class="navbar-nav">
                <li class="nav-item">
                    @Html.ActionLink("Home", "Index", "Home", null, new { @class = "navItem" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("About", "About", "Home", null, new { @class = "navItem" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Contact", "Contact", "Home", null, new { @class = "navItem" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Club Members", "Index", "ClubMember", null, new { @class = "navItem" })
                </li>
            </ul>
        </div>
    </nav>


    <div class="container body-content">
        @RenderBody()
        <hr />
        <!--  Footer -->
        <footer class="main-footer">
            <div class="container-fluid">
                <div class="footer">
                    <div class="row">

                        <div class="col">
                            <p><strong>Louisville Kendo Club</strong><br>1932 Production Dr<br>Louisville, KY 40205</p>
                        </div>

                        <div class="col">
                            <div class="d-flex justify-content-end">
                                <a href="index.html"><img src="@Url.Content("~/Content/MyImg/other/")LKC_logo_green.png" style="width:75px; height:75px;"></a>
                                <a href="http://auskf.org/"><img src="@Url.Content("~/Content/MyImg/other/")auskfLogo.gif" style="width:75px; height:75px;"></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>